name: "Desafio WF"
on:
  push:
    branches:
      - develop

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
            python-version: "3.11"
      - name: "Install pip dependencies"
        run: pip install -r requirements.txt
      - name: "Run test"
        run: PYTHONPATH=. pytest | tee test.log
      - name: "Upload test results"
        uses: actions/upload-artifact@v4
        with:
          name: upload-test
          path: "*.log"
  build_check:
    runs-on: ubuntu-latest
    needs: run_test
    steps:
      - name: "Print build status"
        run: echo "Test successfully run"
  


